workflows:
  ios-release:
    name: iOS Release
    max_build_duration: 30
    instance_type: mac_mini_m2
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      groups:
        - ios_signing
    scripts:
      - name: Set up code signing
        script: |
          # Save private key to file
          echo -n "$CM_CERTIFICATE_KEY" | base64 --decode > /tmp/cert_key.pem
          # Fetch signing files from Apple using API key + certificate private key
          app-store-connect fetch-signing-files "com.kakeibo.kakeibostyle" \
            --type IOS_APP_STORE \
            --certificate-key=@file:/tmp/cert_key.pem \
            --create
          keychain initialize
          keychain add-certificates
          xcode-project use-profiles
      - name: Get Flutter packages
        script: flutter pub get
      - name: Build IPA
        script: flutter build ipa --release --obfuscate --split-debug-info=build/debug-info --export-options-plist=/Users/builder/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
      - build/debug-info/**
    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true

  android-release:
    name: Android Release
    max_build_duration: 30
    instance_type: mac_mini_m2
    environment:
      flutter: stable
      groups:
        - android_signing
    scripts:
      - name: Set up key.properties
        script: |
          echo "storePassword=$CM_KEYSTORE_PASSWORD" >> android/key.properties
          echo "keyPassword=$CM_KEY_PASSWORD" >> android/key.properties
          echo "keyAlias=$CM_KEY_ALIAS" >> android/key.properties
          echo "storeFile=$CM_KEYSTORE_PATH" >> android/key.properties
      - name: Get Flutter packages
        script: flutter pub get
      - name: Build AAB
        script: flutter build appbundle --release --obfuscate --split-debug-info=build/debug-info
      - name: Build APK
        script: flutter build apk --release --obfuscate --split-debug-info=build/debug-info
    artifacts:
      - build/app/outputs/bundle/release/*.aab
      - build/app/outputs/flutter-apk/*.apk
      - build/debug-info/**
    publishing:
      google_play:
        credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
        track: internal
