workflows:
  ios-release:
    name: iOS Release
    max_build_duration: 30
    instance_type: mac_mini_m2
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      groups:
        - ios_signing
    scripts:
      - name: Set up code signing
        script: |
          keychain initialize
          echo -n "$CM_CERTIFICATE" | base64 --decode > /tmp/certificate.p12
          keychain add-certificates --certificate /tmp/certificate.p12
          echo -n "$CM_PROVISIONING_PROFILE" | base64 --decode > /tmp/profile.mobileprovision
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          PROFILE_UUID=$(security cms -D -i /tmp/profile.mobileprovision | plutil -extract UUID raw -)
          cp /tmp/profile.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/${PROFILE_UUID}.mobileprovision
          echo "Installed profile UUID: $PROFILE_UUID"
          xcode-project use-profiles
          # Write export options with no indentation
          printf '<?xml version="1.0" encoding="UTF-8"?>\n<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">\n<plist version="1.0">\n<dict>\n<key>method</key>\n<string>app-store-connect</string>\n<key>teamID</key>\n<string>P8D9M6X786</string>\n<key>signingCertificate</key>\n<string>Apple Distribution</string>\n<key>signingStyle</key>\n<string>manual</string>\n<key>provisioningProfiles</key>\n<dict>\n<key>com.kakeibo.kakeibostyle</key>\n<string>%s</string>\n</dict>\n</dict>\n</plist>' "$PROFILE_UUID" > /tmp/export_options.plist
          cat /tmp/export_options.plist
      - name: Get Flutter packages
        script: flutter pub get
      - name: Build IPA
        script: flutter build ipa --release --export-options-plist=/tmp/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true
