workflows:
  ios-release:
    name: iOS Release
    max_build_duration: 30
    instance_type: mac_mini_m2
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      groups:
        - ios_signing
    scripts:
      - name: Set up code signing
        script: |
          keychain initialize
          echo -n "$CM_CERTIFICATE" | base64 --decode > /tmp/certificate.p12
          keychain add-certificates \
            --certificate /tmp/certificate.p12
          echo -n "$CM_PROVISIONING_PROFILE" | base64 --decode > /tmp/profile.mobileprovision
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          PROFILE_UUID=$(security cms -D -i /tmp/profile.mobileprovision | plutil -extract UUID raw -)
          cp /tmp/profile.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/${PROFILE_UUID}.mobileprovision
      - name: Set Xcode signing to manual
        script: |
          cd ios
          xcodebuild -project Runner.xcodeproj \
            -scheme Runner \
            -showBuildSettings > /dev/null 2>&1 || true
          # Override signing settings in pbxproj
          sed -i '' 's/CODE_SIGN_STYLE = Automatic/CODE_SIGN_STYLE = Manual/g' Runner.xcodeproj/project.pbxproj
          sed -i '' 's/"iPhone Developer"/"Apple Distribution"/g' Runner.xcodeproj/project.pbxproj
      - name: Create export options
        script: |
          cat > /tmp/export_options.plist << 'PLIST'
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
              <key>method</key>
              <string>app-store-connect</string>
              <key>teamID</key>
              <string>P8D9M6X786</string>
              <key>signingStyle</key>
              <string>manual</string>
              <key>provisioningProfiles</key>
              <dict>
                  <key>com.kakeibo.kakeibostyle</key>
                  <string>Kakeibo Style App Store</string>
              </dict>
          </dict>
          </plist>
          PLIST
      - name: Get Flutter packages
        script: flutter pub get
      - name: Build IPA
        script: |
          flutter build ipa --release \
            --export-options-plist=/tmp/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true
